name: 'Azure CD Workflow'

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  checks: write
  actions: write
  packages: read

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      iupipes-config-path:
        required: false
        type: string
        default: '.iupipes.yml'
      infra-working-directory:
        required: false
        type: string
        default: 'infra'
      infra-terraform-version:
        required: false
        type: string
        default: '1.1.9'
      infra-terragrunt-version:
        required: false
        type: string
        default: 'v0.45.16'
      environment:
        required: true
        type: string

jobs:
  # This workflow contains a single job called "greet"
  cd:
    environment: 
      name: ${{ inputs.environment }}
    # The type of runner that the job will run on
    runs-on: ${{ inputs.runs-on }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Runs a single command using the runners shell
    - name: Verify changed files
      uses: tj-actions/verify-changed-files@v20
      id: verify-changed-files
      with:
        files: |
           *.hcl

    - name: Run step only when any of the above files change.
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      env:
        CHANGED_FILES: ${{ steps.verify-changed-files.outputs.changed_files }}
      run: |
        echo "Changed files: $CHANGED_FILES"